Internship/Internship/src/objects/Coefficients__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Coefficient_for_rating__c</fullName>
        <label>Coefficient for rating</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Сoefficients</label>
</CustomObject>

Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Homework__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Homeworks</relationshipLabel>
        <relationshipName>Homeworks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Homework__c.object
<CustomObject>
    <fields>
        <fullName>Homework__c</fullName>
        <label>Homework</label>
        <referenceTo>Homework__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mark__c</fullName>
        <label>Mark</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Homework Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homework Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Test__c.object
<CustomObject>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mark__c</fullName>
        <label>Mark</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Test Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/classes/RecountRatingScheduleJobTest.cls
@isTest
public class RecountRatingScheduleJobTest {
	@isTest
    public static void test(){
        RecountRatingScheduleJobTest.setupData();
        
        List<Coefficients__c> coefficients = new List<Coefficients__c>();
        Coefficients__c Trailhead = new Coefficients__c(Name = 'Trailhead', Coefficient_for_rating__c = 30.0);
        Coefficients__c HomeworkMarks = new Coefficients__c(Name = 'Homework marks', Coefficient_for_rating__c = 30.0);
        Coefficients__c Testsresults = new Coefficients__c(Name = 'Tests results', Coefficient_for_rating__c = 40.0);
        coefficients.add(Trailhead);
        coefficients.add(HomeworkMarks);
        coefficients.add(Testsresults);
        insert coefficients;
        
        System.Test.startTest();
        String jobId = System.schedule('RecountRatingScheduleJobTest','0 0 0 15 3 ? 2022', new RecountRatingScheduleJob());
        System.Test.stopTest();
        
        List<Intern__c> internsToCheck = [SELECT Id, Rating__c FROM Intern__c];
        for(Intern__c intern : internsToCheck){
            System.debug(intern.Rating__c);
        	System.assert(intern.Rating__c != 0 && intern.Rating__c != null);
        }
    }
    
    @isTest
    private static void setupData(){
        Group__c testGroup = sObjectFactory.getGroups(1, Date.today(), Date.today().addMonths(2))[0];
        insert testGroup;
        
        List<Intern__c> testInterns = sObjectFactory.getInterns(10, testGroup.Id, 'test@test.com');
        insert testInterns;
        
        List<Homework__c> testHomeworks = sObjectFactory.getHomeworks(10, testGroup.Id, DateTime.now(), 'topics');
        insert testHomeworks;
        
        List<Test__c> testTests = sObjectFactory.getTests(10, testGroup.Id, DateTime.now(), 'topics');
        insert testTests;
        
        List<Junction_Intern_Homework__c> Junction_Intern_Homeworks = 
            [SELECT Id, Mark__c FROM Junction_Intern_Homework__c WHERE Intern__c IN :testInterns AND Homework__c IN :testHomeworks];
        List<Junction_Intern_Test__c> Junction_Intern_Tests = 
            [SELECT Id, Mark__c FROM Junction_Intern_Test__c WHERE Intern__c IN :testInterns AND Test__c IN :testTests];
        
        for(Junction_Intern_Homework__c Junction_Intern_Homework : Junction_Intern_Homeworks){
            Junction_Intern_Homework.Mark__c = Math.round(Math.random()*100);
        }
        update Junction_Intern_Homeworks;
        
        for(Junction_Intern_Test__c Junction_Intern_Test : Junction_Intern_Tests){
            Junction_Intern_Test.Mark__c = Math.round(Math.random()*100);
        }
        update Junction_Intern_Tests;
    }
}