Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Homework__c.object
<CustomObject>
    <fields>
        <fullName>DeadLine__c</fullName>
        <label>DeadLine</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Homeworks</relationshipLabel>
        <relationshipName>Homeworks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lecturer_Name__c</fullName>
        <label>Lecturer`s name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lecturer_email__c</fullName>
        <label>Lecturer`s email</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lecturer_other_contacts__c</fullName>
        <label>Lecturer`s other contacts</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lecturer_skype_id__c</fullName>
        <label>Lecturer`s skype id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <label>Topics</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Login_for_org__c</fullName>
        <label>Login for org</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Password_for_org__c</fullName>
        <label>Password for org</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Progress__c</fullName>
        <label>Progress</label>
        <picklist>
            <picklistValues>
                <fullName>Hight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Middle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Skype_id__c</fullName>
        <label>Skype id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Trailhead_Progress__c</fullName>
        <label>Trailhead Progress</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Homework__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Homework__c</fullName>
        <label>Homework</label>
        <referenceTo>Homework__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mark__c</fullName>
        <label>Mark</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Sended__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sended</label>
        <type>Checkbox</type>
    </fields>
    <label>Homework Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homework Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Test__c.object
<CustomObject>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mark__c</fullName>
        <label>Mark</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Test Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Resourses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resourсe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lecturer_Name__c</fullName>
        <label>Lecturer`s Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <label>Topics</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/classes/InternHomePageController.cls
public class InternHomePageController{
    public InternWrapper intern {get;set;}
    public Boolean Editable {get;set;}
    public List<HomeworkWrapper> homeworks {get;set;}
    public List<TestWrapper> tests {get;set;}
    public List<ResourceWrapper> resources {get;set;}
    public Integer countHomework {get;set;}
    public Integer countTest {get;set;}
    public Integer countResource {get;set;}
    public String selected {get;set;}
    
    private String questId;
    private List<Homework__c> HomeworksPrivate;
    private List<Junction_Intern_Homework__c> JunctionHomeworks;
    private List<Test__c> TestsPrivate;
    private List<Junction_Intern_Test__c> JunctionTests;
    private List<Resource__c> PrivateResources;
    
    public InternHomePageController(){
        questId = ApexPages.currentPage().getParameters().get('id');
        intern = new InternWrapper([SELECT Name, Email__c, Phone__c, Skype_id__c, Group__c, Rating__c, Trailhead_Progress__c, Progress__c, Login_for_org__c, Password_for_org__c FROM Intern__c WHERE Id = :questId][0]);
        Editable = false;
        
        homeworks = new List<HomeworkWrapper>();
        tests = new List<TestWrapper>();
        
        resources = new List<ResourceWrapper>();
        PrivateResources = [SELECT id, Name, Link__c, Description__c FROM Resource__c WHERE Group__c = :intern.GroupId];
        for(Resource__c resource : PrivateResources){
            ResourceWrapper newResourceWrapper = new ResourceWrapper(resource);
            resources.add(newResourceWrapper);
        }
        
        countResource = resources.size();
        
        HomeworksPrivate = [SELECT Id, Name, DeadLine__c, Task__c, Topics__c, Lecturer_name__c, Lecturer_email__c, Lecturer_skype_id__c, Lecturer_other_contacts__c FROM HomeWork__c WHERE Group__c = :intern.GroupId];
        JunctionHomeworks = [SELECT Id, Homework__c, Mark__c, Comment__c, Sended__c FROM Junction_Intern_Homework__c WHERE Intern__c = :questId];
        countHomework = homeworksPrivate.size();
        
        TestsPrivate = [SELECT Id, Name, Date__c, Complexity__c, Topics__c, Lecturer_name__c FROM Test__c WHERE Group__c = :intern.GroupId];
        JunctionTests = [SELECT Id, Test__c, Mark__c FROM Junction_Intern_Test__c WHERE Intern__c = :questId];
        countTest = TestsPrivate.size();
        
        for(Homework__c homework : HomeworksPrivate){
            for(Junction_Intern_Homework__c JunctionHomework : JunctionHomeworks){
                if(JunctionHomework.Homework__c == homework.Id){
                    homeworks.add(new HomeworkWrapper(homework, JunctionHomework)); 
                    break;
                }
            }
        }
        
        for(Test__c test : TestsPrivate){
            for(Junction_Intern_Test__c JunctionTest : JunctionTests){
                if(JunctionTest.Test__c  == test.Id){
                    tests.add(new TestWrapper(test, JunctionTest)); 
                    break;
                }
            }
        }
        
    }
    
    public void edit(){
        Editable = true;
    }
    
    public void cancel(){
        Editable = false;
    }
    
    public void save(){
        try{
            Intern__c intern = new Intern__c(Id = questId, Name = intern.Name, Email__c = intern.email, Phone__c = intern.phone, Group__c = intern.GroupId, 
                Rating__c = intern.Rating, Trailhead_Progress__c = intern.TrailheadProgress, Progress__c = intern.Progress, 
                Login_for_org__c = intern.Login_for_org, Password_for_org__c = intern.Password_for_org);
            update intern;
            Editable = false; } catch (Exception e){ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.FATAL, 'Check information that you have change! There is a mistake!'); System.debug(e); }
    }
    
    public void done(){
        try{
            Homework__c selectedHomework = [SELECT Name, Task__c, Deadline__c, Lecturer_Email__c FROM Homework__c WHERE Id = :selected][0];        
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
            mail.setToAddresses(new String[]{selectedHomework.Lecturer_Email__c});
            mail.setReplyTo(intern.Email); 
            mail.setSenderDisplayName('Done homework'); 
            mail.setSubject('Homework is done'); 
            mail.setPlainTextBody('Homework "' + selectedHomework.Name + '" was done by intern '+ intern.Name + '. Homework has task: "' + selectedHomework.Task__c + '", and deadline is ' + selectedHomework.Deadline__c + '. Intern email: ' + intern.email + '. Please, check this homework!'); 
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        } catch (Exception e) {
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.Severity.FATAL, 'Sorry! There is some problems with sending email to your lecturer. Please, write him/hew email yourself and informate him/her about your done homework.');
            System.debug(e);
            ApexPages.addMessage(errorMessage);
        }

    }
    
    public class InternWrapper{
        public String Name {get;set;}
        public String Email {get;set;}
        public String Phone {get;set;}
        public String Skype_id {get;set;}
        public Id GroupId;
        public String InternshipGroup {get;set;}
        public Decimal Rating {get;set;}
        public Decimal TrailheadProgress {get;set;}
        public String Progress {get;set;}
        public String Login_for_org {get;set;}
        public String Password_for_org {get;set;}
        
        public InternWrapper (Intern__c questIntern){
            Name = questIntern.Name;
            Email = questIntern.Email__c;
            Phone = questIntern.Phone__c; 
            Skype_id = questIntern.Skype_id__c;
            GroupId = questIntern.Group__c;
            Group__c groupOfIntern = [SELECT Name FROM Group__c WHERE id=:questIntern.Group__c];
            InternshipGroup = groupOfIntern.Name; 
            Rating = questIntern.Rating__c; 
            TrailheadProgress = questIntern.Trailhead_Progress__c; 
            Progress = questIntern.Progress__c; 
            Login_for_org = questIntern.Login_for_org__c; 
            Password_for_org = questIntern.Password_for_org__c; 
        }
    }
    
    public class HomeworkWrapper{
        public String Id {get;set;}
        public String Name {get;set;}
        public String Task {get;set;}
        public DateTime Deadline {get;set;}
        public String LecturerName {get;set;}
        public String LecturerEmail {get;set;}
        public String LecturerSkype {get;set;}
        public String LecturerOtherContacts {get;set;}
        public String Topics {get;set;}
        public Boolean isDone {get;set;}
        public Decimal Mark {get;set;}
        public String Comment {get;set;}
        public Boolean Sended {get;set;}
        
        public HomeworkWrapper(Homework__c homework, Junction_Intern_Homework__c junction){
            System.debug(homework.id);
            id = homework.Id;
            Name = homework.Name;
            Task = homework.Task__c;
            Deadline = homework.Deadline__c;
            LecturerName = homework.Lecturer_Name__c;
            LecturerEmail = homework.Lecturer_Email__c;
            LecturerSkype = homework.Lecturer_skype_id__c;
            LecturerOtherContacts = homework.Lecturer_other_contacts__c;
            Topics = homework.Topics__c;
            isDone = (junction.Mark__c != 0);
            Sended = false;
            Mark = junction.Mark__c;
            Comment = junction.Comment__c;
            Sended = junction.Sended__c;
        }
    }
    
    public class TestWrapper{
        public String Name {get;set;}
        public DateTime TestDate {get;set;}
        public Decimal Complexity {get;set;}
        public String LecturerName {get;set;}
        public String Topics {get;set;}
        public Decimal Mark {get;set;}
        
        public TestWrapper(Test__c test, Junction_Intern_Test__c junction){
            Name = test.Name;
            TestDate = test.Date__c;
            Complexity = test.Complexity__c;
            LecturerName = test.Lecturer_Name__c;
            Topics = test.Topics__c;
            Mark = junction.Mark__c;
        }
    }
    
    public class ResourceWrapper{
        public string Name {get;set;}
        public String Link {get;set;}
        public String Description {get; set;}
        
        public ResourceWrapper(Resource__c resource){
            Name = resource.Name;
            Link = resource.Link__c;
            Description  = resource.Description__c;
        }
    }
}