Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Homework__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Homeworks</relationshipLabel>
        <relationshipName>Homeworks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Homework__c.object
<CustomObject>
    <fields>
        <fullName>Comment__c</fullName>
        <label>Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Homework__c</fullName>
        <label>Homework</label>
        <referenceTo>Homework__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mark__c</fullName>
        <label>Mark</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Homework Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homework Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/classes/HomeworkHandler.cls
public class HomeworkHandler {
    public static void afterInsert(List<Homework__c> homeworks){
        
        Set<Id> groupIds = new Set<Id>();
        for(Homework__c homework : homeworks){
            groupIds.add(homework.Group__c);
        }
        
        List<Intern__c> interns = [SELECT Id, Group__c FROM Intern__c WHERE Group__c IN :groupIds];
        
        Map<Id, List<Intern__c>> internsByGroup = new Map<Id, List<Intern__c>>();
        for(Intern__c intern : interns){
            if(internsByGroup.containsKey(intern.Group__c)){
                internsByGroup.get(intern.Group__c).add(intern);
            } else {
                internsByGroup.put(intern.Group__c, new List<Intern__c>{intern});
            }
        }
        
        List<Junction_Intern_Homework__c> newJunction_Intern_Homeworks = new List<Junction_Intern_Homework__c>();
        for(Homework__c homework : homeworks){
            for(Intern__c intern : internsByGroup.get(homework.Group__c)){
                Junction_Intern_Homework__c newJunction_Intern_Homework = new Junction_Intern_Homework__c(Intern__c = intern.Id, Homework__c = homework.Id, Mark__c = 0, Comment__c = '');
                newJunction_Intern_Homeworks.add(newJunction_Intern_Homework);
            }
        }
        insert newJunction_Intern_Homeworks;
    }
}