Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Test__c.object
<CustomObject>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Test Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/classes/TestTriggerTest.cls
@isTest
public class TestTriggerTest {
    @isTest
    public static void afterInsertTest(){
        Group__c testGroup = sObjectFactory.getGroups(1, Date.today(), Date.today().addMonths(1))[0];
        insert testGroup;
        List<Intern__c> testInterns = sObjectFactory.getInterns(10, testGroup.Id, 'test@test.com');
        insert testInterns;
        List<Test__c> testTests = sObjectFactory.getTests(200, testGroup.Id, DateTime.now().addDays(5), 'topics');
        
        System.Test.startTest();
        insert testTests;
        System.Test.stopTest();
        
        List<Test__c> testTestsToCheck = [SELECT Id FROM Test__c WHERE Group__c = :testGroup.Id];
        List<Junction_Intern_Test__c> Junction_Intern_TestToCheck = 
            [SELECT Id FROM Junction_Intern_Test__c WHERE Intern__c IN :testInterns AND Test__c IN :testTestsToCheck];
        System.assertEquals(200, testTestsToCheck.size());
        System.assertEquals(2000, Junction_Intern_TestToCheck.size());
    }
}