Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Final_Date__c</fullName>
        <label>Final Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Homework__c.object
<CustomObject>
    <fields>
        <fullName>DeadLine__c</fullName>
        <label>DeadLine</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Homeworks</relationshipLabel>
        <relationshipName>Homeworks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lecturer_Name__c</fullName>
        <label>Lecturer`s name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <label>Topics</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Login_for_org__c</fullName>
        <label>Login for org</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Password_for_org__c</fullName>
        <label>Password for org</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Skype_id__c</fullName>
        <label>Skype id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Trailhead_Progress__c</fullName>
        <label>Trailhead Progress</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Resourses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Link__c</fullName>
        <label>Link</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resourсe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Complexity__c</fullName>
        <label>Complexity</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lecturer_Name__c</fullName>
        <label>Lecturer`s Name</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Topics__c</fullName>
        <label>Topics</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/classes/sObjectFactory.cls
public class sObjectFactory {
    public static List<Homework__c> getHomeworks(Integer countOfRequiredRecords, Id GroupId, DateTime DeadLine, String topics){
        List<Homework__c> newHomeworks = new List<Homework__c>();
        for(Integer i = 0; i < countOfRequiredRecords; i++){
            Homework__c newHomework = new Homework__c(Group__c = GroupId, DeadLine__c = DeadLine, Topics__c = topics);
            newHomeworks.add(newHomework);
        }
        return newHomeworks;
    }
    
    public static List<Test__c> getTests(Integer countOfRequiredRecords, Id GroupId, DateTime MyDate, String topics){
        List<Test__c> newTests = new List<Test__c>();
        for(Integer i = 0; i < countOfRequiredRecords; i++){
            Test__c newTest = new Test__c(Group__c = GroupId, Date__c = MyDate, Topics__c = topics, Complexity__c = 0, Lecturer_Name__c = 'test Lecturer`s Name');
            newTests.add(newTest);
        }
        return newTests;
    }
    
    public static List<Group__c> getGroups(Integer countOfRequiredRecords, Date StartDate, Date FinalDate){
        List<Group__c> newGroups = new List<Group__c>();
        for(Integer i = 0; i < countOfRequiredRecords; i++){
            Group__c newGroup = new Group__c(Start_Date__c = StartDate, Final_Date__c = FinalDate);
            newGroups.add(newGroup);
        }
        return newGroups;
    }
    public static List<Intern__c> getInterns(Integer countOfRequiredRecords, Id GroupId, String email){
        List<Intern__c> newInterns = new List<Intern__c>();
        for(Integer i = 0; i < countOfRequiredRecords; i++){
            Intern__c newIntern = new Intern__c(Group__c = GroupId, Email__c = i + email, Skype_id__c = 'test.skype.id' + i, Login_for_org__c = i + email, Password_for_org__c = 'Password', 
                                                Trailhead_Progress__c = 100 * Math.round(Math.random()*1000));
            newInterns.add(newIntern);
        }
        return newInterns;
    }
    
    public static List<Resource__c> getResources(Integer countOfRequiredRecords, Id GroupId, String Link){
        List<Resource__c> newResources = new List<Resource__c>();
        for(Integer i = 0; i < countOfRequiredRecords; i++){
            Resource__c newResource = new Resource__c(Name = 'Test '+i, Group__c = GroupId, Link__c = Link);
            newResources.add(newResource);
        }
        return newResources;
    }
}