Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Homework__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Homeworks</relationshipLabel>
        <relationshipName>Homeworks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/classes/HomeworkPageControllerTest.cls
@isTest
public class HomeworkPageControllerTest {
	@isTest
    public static void test(){
        Group__c newGroup = sObjectFactory.getGroups(1, Date.today(), Date.today().addMonths(1))[0];
        insert newGroup;
        List<Intern__c> newInterns = sObjectFactory.getInterns(10, newGroup.Id, 'test@test.com');
        insert newInterns;
        List<Homework__c> newHomeworks = sObjectFactory.getHomeworks(10, newGroup.Id, Date.today().addMonths(1), 'topics');
        insert newHomeworks;
        
        System.test.startTest();
        HomeworkPageController testHomeworkPageController = new HomeworkPageController();
        System.Test.stopTest();
        
        System.assertEquals(newHomeworks.size(), HomeworkPageController.countHomework);
    }
}