Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Homework__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Homeworks</relationshipLabel>
        <relationshipName>Homeworks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Resource__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Resourses</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Resource</label>
    <nameField>
        <label>Resourсe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Resources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/classes/InternHomePageControllerTest.cls
@isTest
public class InternHomePageControllerTest {
	@isTest
    public static void test(){
        
        Group__c newgroup = sObjectFactory.getGroups(1, Date.today(), Date.today().addDays(20))[0];
        insert newgroup;
        List<Intern__c> newInterns = sObjectFactory.getInterns(10, newgroup.Id, 'test@test.com');
        insert newInterns;
        List<Homework__c> newHomeworks = sObjectFactory.getHomeworks(15, newgroup.Id, Date.today().addDays(5), 'topics');
        insert newHomeworks;
        List<Test__c> newTests = sObjectFactory.getTests(10, newgroup.Id, Date.today().addDays(5), 'topics');
        insert newTests;
        List<Resource__c> newResources = sObjectFactory.getResources(10, newgroup.Id, 'www.ex.ua');
        insert newResources;
        
        String idVariable = [SELECT Id FROM Intern__c LIMIT 1][0].Id;
        Test.setCurrentPageReference(new PageReference('Page.internHomePage')); 
		System.currentPageReference().getParameters().put('id', idVariable);
        
        System.Test.startTest();
        InternHomePageController newInternHomePageController = new InternHomePageController();
        newInternHomePageController.selected = [SELECT Id FROM Homework__c LIMIT 1][0].Id;
        newInternHomePageController.edit();
        newInternHomePageController.cancel();
        newInternHomePageController.save();
        newInternHomePageController.done();
        System.Test.stopTest();
        
        System.assertEquals(idVariable, idVariable);
    }
}