Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Test__c.object
<CustomObject>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Mark__c</fullName>
        <label>Mark</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Test__c</fullName>
        <label>Test</label>
        <referenceTo>Test__c</referenceTo>
        <relationshipName>Junction_Intern_Test</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Test Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Test Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/classes/TestHandler.cls
public class TestHandler {
    public static void afterInsert(List<Test__c> tests){
        
        Set<Id> groupIds = new Set<Id>();
        for(Test__c test : tests){
            groupIds.add(test.Group__c);
        }
        
        List<Intern__c> interns = [SELECT Id, Group__c FROM Intern__c WHERE Group__c IN :groupIds];
        
        Map<Id, List<Intern__c>> internsByGroup = new Map<Id, List<Intern__c>>();
        for(Intern__c intern : interns){
            if(internsByGroup.containsKey(intern.Group__c)){
                internsByGroup.get(intern.Group__c).add(intern);
            } else {
                internsByGroup.put(intern.Group__c, new List<Intern__c>{intern});
            }
        }
        
        List<Junction_Intern_Test__c> newJunction_Intern_Tests = new List<Junction_Intern_Test__c>();
        for(Test__c test : tests){
            for(Intern__c intern : internsByGroup.get(test.Group__c)){
                Junction_Intern_Test__c Junction_Intern_Test = new Junction_Intern_Test__c(Intern__c = intern.Id, Test__c = test.Id, Mark__c = 0);
                newJunction_Intern_Tests.add(Junction_Intern_Test);
            }
        }
        insert newJunction_Intern_Tests;
    }
}