Internship/Internship/src/objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Homework__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Homeworks</relationshipLabel>
        <relationshipName>Homeworks</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Homework</label>
    <nameField>
        <label>Homework Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homeworks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Intern__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Interns</relationshipLabel>
        <relationshipName>Interns</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Intern</label>
    <nameField>
        <label>Intern Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interns</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

Internship/Internship/src/objects/Junction_Intern_Homework__c.object
<CustomObject>
    <fields>
        <fullName>Homework__c</fullName>
        <label>Homework</label>
        <referenceTo>Homework__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Intern__c</fullName>
        <label>Intern</label>
        <referenceTo>Intern__c</referenceTo>
        <relationshipName>Junction_Intern_Homework</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Homework Mark</label>
    <nameField>
        <label>Mark Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Homework Marks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Internship/Internship/src/classes/HomeworkTriggerTest.cls
@isTest
public class HomeworkTriggerTest {
    @isTest
    public static void afterInsertTest(){
        Group__c testGroup = sObjectFactory.getGroups(1, Date.today(), Date.today().addMonths(1))[0];
        insert testGroup;
        List<Intern__c> testInterns = sObjectFactory.getInterns(10, testGroup.Id, 'test@test.com');
        insert testInterns;
        List<Homework__c> testHomeworks = sObjectFactory.getHomeworks(200, testGroup.Id, DateTime.now().addDays(5), 'topics');
        
        System.Test.startTest();
        insert testHomeworks;
        System.Test.stopTest();
        
        List<Homework__c> testHomeworksToCheck = [SELECT Id FROM Homework__c WHERE Group__c = :testGroup.Id];
        List<Junction_Intern_Homework__c> Junction_Intern_HomeworkToCheck = 
            [SELECT Id FROM Junction_Intern_Homework__c WHERE Intern__c IN :testInterns AND Homework__c IN :testHomeworksToCheck];
        System.assertEquals(200, testHomeworksToCheck.size());
        System.assertEquals(2000, Junction_Intern_HomeworkToCheck.size());
    }
}